### PR TITLE
Multiple keyboard support added

### PR DESCRIPTION
**Pull request by DavRack**
Multiple keyboard support has been added.
Each keyboard needs a config file, the main program SKR will iterate over each config file and launch a instance of skrcore with that config file (previously this was the main program but i have made some changes).

+ Now the --init option is executed in python
+ Now the --init option ask for a config file name

I've test it with two keyboards and works great for my but would be nice to get some feedback if someone can test it with more devices.

### CODE REVIEW

**Comment by gnufied** [comment]
does it work for hotplugged devices? Assuming device path did not change? I need to investigate but there is some bug somewhere in code which causes skr to take 100% CPU when keyboard changes or something. 

It does appear to work if you restart skr each time after plugging a USB keyboard and such.

**Comment by gnufied** [comment]
Also I hope the code handles the case of a keyboard suddenly going away gracefully and does not result in some of no-op loop.

**Comment by DavRack** [comment]
I've confirmed the 100% CPU usage bug, a fix and a hotplug implementation has been added. Im going to test it with two keyboards but it's seems to work fine for one.

**Comment by DavRack** [comment]
seems to work fine with two keyboards too and hotplugging, pls test it

**Comment by pstonham** [comment]
yep, hotplugging seems to work and no 100 cpu, nice work.

**Comment by gnufied** [comment]
Yeah it seems to be working fine. BTW - is there some delay sometimes in processing keyboard events? I sometimes get 2-3 seconds freeze between key pressed and stuff happening. I haven't yet figured it out if it is my machine or skr.

**Comment by DavRack** [comment]
there's no delay i get less than 1ms of latency on my machine even with tow keyboards

**Pull request merged**
